name: Cek Akun Aktif

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          sudo mkdir -p /usr/local/bin
          curl -L https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip -o xray.zip
          sudo apt-get update && sudo apt-get install -y unzip curl
          unzip xray.zip -d xray
          sudo mv xray/xray /usr/local/bin/xray
          sudo chmod +x /usr/local/bin/xray

      - name: Run checker
        run: |
          python checker.py

      - name: Commit hasil
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add active_all.txt
          git commit -m "Update hasil active_all.txt" || echo "Tidak ada perubahan"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
