name: Sortir Akun Aktif

on:
  workflow_dispatch: # manual
  schedule:
    - cron: "0 */6 * * *" # otomatis tiap 6 jam

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Jalankan checker
        run: python checker.py

      - name: Commit hasil aktif
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add active_all.txt
          git commit -m "Update hasil active_all.txt" || echo "No changes"
          git push
