name: Sortir Akun Aktif

on:
  workflow_dispatch: # Bisa dijalankan manual
  schedule:
    - cron: "0 */6 * * *" # Otomatis tiap 6 jam

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Jangan pakai default GITHUB_TOKEN

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Install dependencies
      - name: Install dependencies
        run: pip install requests

      # 4. Jalankan checker.py
      - name: Jalankan checker
        run: python checker.py

      # 5. Commit hasil ke repo
      - name: Commit hasil aktif
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git add active_all.txt
          git commit -m "Update hasil active_all.txt" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
